# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 79987b88c8b92cadcd2267e091adbc2ea539f730e1e806be57ea2935bed49e937bb17bd503349a2111cb6b165b9117acf3e20f43102e9c63a5576514acdb2e92

test:
  secret_key_base: e2a75a7c25ae182047c39af9ccc865f72b50ed49bc58dfe2cac27ee43144f1a8bf399223c17065f4f715ac152a37ffa18600f02d11e1b17c04617e76f19f3642

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
